version: '3'

services:
  python_proxy:
    image: nginx:latest
    container_name: python_proxy
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./logs/nginx:/var/log/nginx
      - ./certs:/etc/letsencrypt
      - ./certs-data:/data/letsencrypt
    depends_on:
      - python_backend
    links:
      - python_backend
    restart: always

  python_backend:
    container_name: python_backend
    build:
      context: .
      dockerfile: python-backend/Dockerfile
    ports:
     - "8000:8000"
    volumes:
      - ./app/pos-backend-py:/app
    restart: always

